### ISSUE TITLE
Opencm9.04 arduino ide ver?

### ISSUE THREAD

**Issue by funfun2** [KurtE/Open_CM904#1]
upload successful.... ♥
opencm port detection failure T.T
Fortunately, firmware recovery

**Comment by KurtE** [comment]
Upload of what?  There are a few different test programs here 

But if the question is, what version of Arduino IDE... I use 1.8.5, 
I have Robotis OpenCM9.04 board version 1.1.0 installed.

Or alternatively I build with latest Robotis development stuff.  More on how I do that is up on
https://community.robotsource.org/t/opencm-9-04-how-to-build-using-the-develop-branch-and-make-pull-requests/1474

**Comment by funfun2** [comment]
WoW cool

**Comment by funfun2** [comment]
arduino ide 1.85, opencm9.04 1.1.0 ver has been fixed through the board manager url.

-----------------------------------------
opencm9.04 Upload was successful, but I can not edit it.
Ps2pad created in arbotix commander format.
ps2pad is only using tx.
opencm9.04 is using only rx signal Serial2.begin (57600).
What should I change.

**Comment by KurtE** [comment]
Serial2 works for both RX and TX.  I don't know ps2pad... I have an XBee Adapter that I have plugged into the Serial2 port, which I use to received messages from an Arbotix Commander... Been awhile since I tried it,  Will probably do so again soon as I get back to working with Hexapod...

Suggest if you have questions on how the OpenCM 9.04 works, that you ask questions up on forums or if you have run into issue, create an issue against the OpenCM github project:

Forums: http://en.robotis.com/service/forum.php or http://forums.trossenrobotics.com/forum.php

Or for issues: https://github.com/ROBOTIS-GIT/OpenCM9.04/issues

The good thing about the robotis forum or raising issue is that you developers at Robotis try to answer your questions

**Comment by funfun2** [comment]
Connected with hexapod.
However, when the ax-12 + is connected, the id-1 servo stops.
I do not know the cause.
It does not work with another ax-12 + or ax-12a.

(I used DEVICE_NAME "1".
And arbotix_command using Serial2)

**Comment by funfun2** [comment]
I found it.
//#define cLFCoxaPin      19   //Front Left leg Hip Horizontal - Avoid servo 1
Applies necessary corrections to servo angles to account for hardware
